/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4244ca629f6011b823f8b11dd959b509)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
